version: '3'
services:
  nginx:
    container_name: v-nginx
    image: nginx:1.13
    restart: on-failure
    ports:
      - 81:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    
  mysql:
    container_name: v-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3308"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure
    
  app:
    restart: on-failure
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    expose:
      - 8080
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker